application/__init__.py
# -*- coding: utf-8 -*-
import logging

from flask import current_app, Flask, redirect, url_for
from flask import render_template

import settings


def create_app(config, debug=False, testing=False, config_overrides=None):
    app = Flask(__name__, template_folder=settings.TEMPLATE_FOLDER)
    app.config.from_object(config)

    app.debug = debug
    app.testing = testing

    if config_overrides:
        app.config.update(config_overrides)

    # Configure logging
    if not app.testing:
        logging.basicConfig(level=logging.INFO)

    # Register any blueprint.
    from application.hello.views import bp_hello
    app.register_blueprint(bp_hello)

    # [START app.route]
    # Add a default root route.
    @app.route("/")
    def index():
        return redirect(url_for('hello.home'))

    @app.route('/_ah/warmup')
    def warmup():
        """App Engine warmup handler
        See http://code.google.com/appengine/docs/python/config/appconfig.html#Warming_Requests

        """
        return 'success'

    # Error handlers
    # Handle 404 errors
    @app.errorhandler(404)
    def page_not_found(e):
        return render_template('404.html'), 404

    # Handle 500 errors
    @app.errorhandler(500)
    def server_error(e):
        logging.error("!!!! -- server_error -- 500 Internal Server Error")
        # send_error_mail_for_developer(app.config['SENDER_ADDRESS'],
        #                                         app.config['DEVELOPER_MAILS'],
        #                                         "500 Internal Server Error", e)

        app.logger.error(e)
        return render_template('500.html'), 500
    # [END app.route]

    return app

application/hello/views.py
# -*- coding: utf-8 -*-
import logging

from flask import make_response
from flask import render_template
from flask import request, Blueprint
from google.appengine.ext.blobstore import blobstore
from werkzeug.http import parse_options_header

bp_hello = Blueprint('hello', __name__, url_prefix='/hello')


@bp_hello.route('/', methods=['GET'])
def home():
    # Blobstore に保存されているファイルを取得
    files = blobstore.BlobInfo.all()
    return render_template('index.html', files=files)


@bp_hello.route('/upload', methods=['GET'])
def upload():
    upload_url = blobstore.create_upload_url('/hello/upload_photo')
    logging.info(upload_url)
    return render_template('upload.html', upload_url=upload_url)


@bp_hello.route("/upload_photo", methods=['POST'])
def upload_file():
    if request.method == 'POST':

        # File取得
        uploaded_file = request.files['file']
        header = uploaded_file.headers['Content-Type']

        # blob-key取得
        parsed_header = parse_options_header(header)
        blob_key = parsed_header[1]['blob-key']

        return render_template('uploaded_file_link.html', blob_key=blob_key)


@bp_hello.route("/view_photo/<blob_key>", methods=['GET', 'POST'])
def view_photo(blob_key=''):
    blob_info = blobstore.get(blob_key)
    response = make_response(blob_info.open().read())
    response.headers['Content-Type'] = blob_info.content_type
    return response

main.py
#!/usr/bin/env python
#
# Copyright 2007 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import application
from configration import EnvironmentConfig

app = application.create_app(config=EnvironmentConfig, debug=True)

if __name__ == '__main__':
    app.run()

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Hello</title>
</head>
<body>
<h1>Hello</h1>
<a href="{{ url_for('hello.upload') }}">Upload</a>

<h2>Uploaded Files</h2>
<ul>
  {% for file in files %}
  <li><a href="{{ url_for('hello.view_photo', blob_key=file.key()) }}">{{ file.filename }}</a></lI>
  {% endfor %}
</ul>
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
  <title>Upload</title>

</head>
<body>
<h1>Upload</h1>

<form action="{{ upload_url }}" method="POST" enctype="multipart/form-data">
  <div class="form-group">
    <label for="file">Upload File:</label>
    <input type="file" name="file" id="file" required="">
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">送信</button>
  </div>
</form>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>

</body>
</html>

templates/uploaded_file_link.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Uploaded</title>

</head>
<body>
<h1>Upload</h1>

<a href="{{ url_for('hello.view_photo', blob_key=blob_key) }}">{{ url_for('hello.view_photo', blob_key=blob_key) }}</a>

</body>
</html>